---
abstract: 'client side code for perl debugger'
author:
  - 'Gabor Szabo <gabor@szabgab.com>'
  - 'Breno G. de Oliveira <garu at cpan.org>'
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  Exporter: 0
  ExtUtils::MakeMaker: 6.62
  File::HomeDir: 0
  File::Spec: 0
  File::Temp: 0
  Test::Deep: 0.108
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Debug-Client
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
requires:
  Carp: 1.20
  IO::Socket: 1.31
  IO::Socket::INET: 1.31
  PadWalker: 1.92
  perl: 5.008
resources:
  bugtracker: http://padre.perlide.org/trac
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Debug-Client/
version: 0.13_04
