---
abstract: 'debugger client side code for Padre, The Perl IDE.'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::HomeDir: 0.98
  File::Spec: 3.33
  File::Temp: 0.22
  Test::Deep: 0.108
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Debug::Client
name: Debug-Client
no_index:
  directory:
    - eg
    - inc
    - t
    - xt
requires:
  Carp: 1.20
  IO::Socket::IP: 0.17
  PadWalker: 1.92
  Term::ReadLine: 1.07
  Term::ReadLine::Perl: 1.0303
  perl: 5.10.0
resources:
  bugtracker: http://padre.perlide.org/trac/wiki/Tickets
  homepage: http://padre.perlide.org/trac/wiki/Features/Perl5Debugger
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Debug-Client/
version: 0.21_11
